### ISSUE TITLE
Minor bugs in example

### ISSUE THREAD

**Issue by wyrex** [nomad-software/tkd#34]
Hello! 
I decided to try tkd and noticed these things (compiled with ldc2 in linux). Cheers.

 If you click file type filter or directory path button in a dialog clicking the button again won't close the popup and you have to click one of the texts to close it.

![directory](https://cloud.githubusercontent.com/assets/13369724/12156483/c10e6b50-b4d3-11e5-8170-98bb07fdcca1.png)
This one widget goes out of bounds to down/right when moved.

![canvas](https://cloud.githubusercontent.com/assets/13369724/12156487/c3f3cdf6-b4d3-11e5-94fa-da8a5c77d401.png)

**Comment by nomad-software** [comment]
Thanks for the report.

Unfortunately, both of these issues are with Tcl/Tk and not with Tkd. Believe it or not, these are how these items are supposed to work. They also function the same when using Python's Tkinter library. So there's nothing I can do to fix them.
