### ISSUE TITLE
Problem with unicode not being used for file and directory dialogs.

### ISSUE THREAD

**Issue by nomad-software** [nomad-software/tkd#36]
Hi,

I'm the d-apt maintainer. I noticed that when running the example, the open file and Directory dialogs do not properly show the file/folder names if they include some accent or another diacritical mark. Is TkD dialogs non compatible with UTF-8?

Here attach you some captures from Debian.

![captura-open](https://cloud.githubusercontent.com/assets/1413497/12372361/234731fc-bc4b-11e5-91c1-1a08ef7490d0.png)
![captura-choose a directory](https://cloud.githubusercontent.com/assets/1413497/12372362/23499bd6-bc4b-11e5-8666-c7d27632bdf7.png)

Regards,
Jordi

**Comment by KarlHeesch** [comment]
It seams that insertion of `_tk.eval("encoding system utf-8"); ` into constructor of `class TkdApplication` could help. At least with Linux it worked for me.
Regards, Karl

**Comment by nomad-software** [comment]
Fixed in commit https://github.com/nomad-software/tkd/commit/6b94a0bc9882f7d9d0d70708377ca42bc4ee3e2a

**Comment by jordisayol** [comment]
It properly works on Linux. Thank you!
