### ISSUE TITLE
Menu Alt-Shortcut not working in example.

### ISSUE THREAD

**Issue by KarlHeesch** [nomad-software/tkd#37]
In the example application entering a menu shortcut, e.g. `Alt-F`  issues an error.
The message is:
```
grab failed: window not viewable
grab failed: window not viewable
    while executing
"grab -global $w"
    (procedure "tk::TraverseToMenu" line 20)
    invoked from within
"tk::TraverseToMenu .frame-F4FBE983.labelframe-3920BD3D.text-49FBE756 f"
    (command bound to event)
```
Happens on ubuntu with dmd.

Regards,
Karl

**Comment by nomad-software** [comment]
Fixed in commit https://github.com/nomad-software/tkd/commit/f328033232615147be42f50c0102b8a0c8fe0e76

Reference: http://rkeene.org/projects/tcl/tk.fossil/tkthistory/530491ffff
