### ISSUE TITLE
Build of example fails on Mac OSX 10.11

### ISSUE THREAD

**Issue by aaronhyperum** [nomad-software/tkd#39]
Multiple assertion failures. The terminal output looks really obfuscated, so I have no idea how to begin.

    Home$ dub --config=example
    Fetching tcltk 8.6.5 (getting selected version)...
    Placing tcltk 8.6.5 to /Users/Home/.dub/packages/...
    Fetching x11 1.0.13 (getting selected version)...
    Placing x11 1.0.13 to /Users/Home/.dub/packages/...
    Building x11 1.0.13 configuration "tcltk-import", build type debug.
    Running dmd...
    Building tcltk 8.6.5 configuration "library", build type debug.
    Running dmd...
    Building tkd ~master configuration "example", build type debug.
    Compiling using dmd...
    Linking...
    Running ./build/example/example 
    2016-03-14 16:15:25.515 example[57378:443596] *** Assertion failure in -[NSBitmapImageRep initWithCGImage:], /Library/Caches/com.apple.xbs/Sources/AppKit/AppKit-    1404.34/AppKit.subproj/NSBitmapImageRep.m:1289
    2016-03-14 16:15:25.536 example[57378:443596] An uncaught exception was raised
    2016-03-14 16:15:25.537 example[57378:443596] Invalid parameter not satisfying: cgImage != NULL
    2016-03-14 16:15:25.537 example[57378:443596] (
    	0   CoreFoundation                      0x00007fff91be0ae2 __exceptionPreprocess + 178
    	1   libobjc.A.dylib                     0x00007fff86bee73c objc_exception_throw + 48
    	2   CoreFoundation                      0x00007fff91be08ba +[NSException raise:format:arguments:] +     106
    	3   Foundation                          0x00007fff887d688c -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 198
    	4   AppKit                              0x00007fff9104385f -[NSBitmapImageRep initWithCGImage:] + 149
    	5   Tk                                  0x000000010bc615f4 TkPutImage + 1750
    	6   Tk                                  0x000000010bc6155e TkPutImage + 1600
    	7   Tk                                  0x000000010bc693f5 TkMacOSXClearMenubarActive + 3046
        8   Tk                                  0x000000010bbf1a11 TkSetWindowMenuBar + 10987
    	9   Tk                                  0x000000010bbf0d00 TkSetWindowMenuBar + 7642
    	10  Tk                                  0x000000010bbf0e53 TkSetWindowMenuBar + 7981
    	11  Tk                                  0x000000010bbf0320 TkSetWindowMenuBar + 5114
    	12  Tcl                                 0x000000010bad645a Tcl_ListMathFuncs + 1981
    	13  Tcl                                 0x000000010bad7633 Tcl_EvalEx + 1941
    	14  Tcl                                 0x000000010bad6eb8 Tcl_EvalEx + 26
    	15  example                             0x000000010b655727 D3tkd11interpreter3tcl3Tcl9__T4evalZ4evalMFNbAyaZv + 147
    	16  example                             0x000000010b6ab480 D3tkd6widget4menu4menu4Menu41__T8addEntryTC3tkd6widget4menu4menu4MenuZ8addEntryMFC3tkd5image5image5ImageAyaDFS3tkd7element7element11CommandArgsZvAyaAyaZC3tkd6widget4menu4menu4Menu + 412
    	17  example                             0x000000010b62dc83 D4main11Application10createMenuMFZv + 1111
    	18  example                             0x000000010b632abc D4main11Application13initInterfaceMFZv + 616
    	19  example                             0x000000010b65801b D3tkd14tkdapplication14TkdApplication6__ctorMFZC3tkd14tkdapplication14TkdApplication + 71
    	20  example                             0x000000010b633169 D4main11Application6__ctorMFZC4main11Application + 21
    	21  example                             0x000000010b629478 _Dmain + 40
    	22  example                             0x000000010b6ca718 D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ6runAllMFZ9__lambda1MFZv + 40
    	23  example                             0x000000010b6ca65d D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ7tryExecMFMDFZvZv + 45
    	24  example                             0x000000010b6ca6bd D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ6runAllMFZv + 45
    	25  example                             0x000000010b6ca65d D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ7tryExecMFMDFZvZv + 45
    	26  example                             0x000000010b6ca5d3 _d_run_main + 499
    	27  example                             0x000000010b629542 main + 34
    	28  libdyld.dylib                       0x00007fff8b5e35ad start + 1
    	29  ???                                 0x0000000000000001 0x0 + 1
    )
    2016-03-14 16:15:25.537 example[57378:443596] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid parameter not satisfying: cgImage != NULL'
    *** First throw call stack:
    (
    	0   CoreFoundation                      0x00007fff91be0ae2 __exceptionPreprocess + 178
    	1   libobjc.A.dylib                     0x00007fff86bee73c objc_exception_throw + 48
    	2   CoreFoundation                      0x00007fff91be08ba +[NSException raise:format:arguments:] + 106
    	3   Foundation                          0x00007fff887d688c -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 198
    	4   AppKit                              0x00007fff9104385f -[NSBitmapImageRep initWithCGImage:] + 149
    	5   Tk                                  0x000000010bc615f4 TkPutImage + 1750
    	6   Tk                                  0x000000010bc6155e TkPutImage + 1600
    	7   Tk                                  0x000000010bc693f5 TkMacOSXClearMenubarActive + 3046
    	8   Tk                                  0x000000010bbf1a11 TkSetWindowMenuBar + 10987
    	9   Tk                                  0x000000010bbf0d00 TkSetWindowMenuBar + 7642
    	10  Tk                                  0x000000010bbf0e53 TkSetWindowMenuBar + 7981
    	11  Tk                                  0x000000010bbf0320 TkSetWindowMenuBar + 5114
    	12  Tcl                                 0x000000010bad645a Tcl_ListMathFuncs + 1981
    	13  Tcl                                 0x000000010bad7633 Tcl_EvalEx + 1941
    	14  Tcl                                 0x000000010bad6eb8 Tcl_EvalEx + 26
    	15  example                             0x000000010b655727 D3tkd11interpreter3tcl3Tcl9__T4evalZ4evalMFNbAyaZv + 147
    	16  example                             0x000000010b6ab480 D3tkd6widget4menu4menu4Menu41__T8addEntryTC3tkd6widget4menu4menu4MenuZ8addEntryMFC3tkd5image5image5ImageAyaDFS3tkd7element7element11CommandArgsZvAyaAyaZC3tkd6widget4menu4menu4Menu + 412
    	17  example                             0x000000010b62dc83 D4main11Application10createMenuMFZv + 1111
    	18  example                             0x000000010b632abc D4main11Application13initInterfaceMFZv + 616
    	19  example                             0x000000010b65801b D3tkd14tkdapplication14TkdApplication6__ctorMFZC3tkd14tkdapplication14TkdApplication + 71
    	20  example                             0x000000010b633169 D4main11Application6__ctorMFZC4main11Application + 21
    	21  example                             0x000000010b629478 _Dmain + 40
    	22  example                             0x000000010b6ca718 D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ6runAllMFZ9__lambda1MFZv + 40
    	23  example                             0x000000010b6ca65d D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ7tryExecMFMDFZvZv + 45
    	24  example                             0x000000010b6ca6bd D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ6runAllMFZv + 45
    	25  example                             0x000000010b6ca65d D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ7tryExecMFMDFZvZv + 45
    	26  example                             0x000000010b6ca5d3 _d_run_main + 499
    	27  example                             0x000000010b629542 main + 34
    	28  libdyld.dylib                       0x00007fff8b5e35ad start + 1
    	29  ???                                 0x0000000000000001 0x0 + 1
    )
    libc++abi.dylib: terminating with uncaught exception of type NSException
    Error executing command run:
    Program exited with code -6

**Comment by nomad-software** [comment]
Please see: https://github.com/nomad-software/tkd/issues/13
