### ISSUE TITLE
Example fails to run on Windows but build fine

### ISSUE THREAD

**Issue by Shadowys** [nomad-software/tkd#41]
The build is successful but when I attempt to run it, two error prompts happen. Both have the same message `tcl86t.dll` is not found. I checked my dub folder in "Appdata/Roaming", and it is found under the dist folder, just fine. 

I had no tcl installation so I went to install Activetcl 8.6, but that dll is not there, and it doesn't run. I downloaded the dll from the internet and placed it in the same folder, and only one error prompts occured. 

Is there a special build link that I should include if I'm using it from Windows?

**Comment by nomad-software** [comment]
Everything you need is in this repository and everything is explained in the readme file
