### ISSUE TITLE
Add note for linker flags in windows needed to prevent console window.

### ISSUE THREAD

**Issue by Shadowys** [nomad-software/tkd#42]
From this thread : http://forum.dlang.org/post/ilgqfn$2536$1@digitalmars.com

`"lflags":[-L/exet:nt/su:windows]` is needed to be added to the dub.json to prevent the console window from appearing.

**Comment by nomad-software** [comment]
I've just tried building the example on Window 10 and Windows 7 and both build and run fine without showing the console. There is already linker flags specified in the dub file here: https://github.com/nomad-software/tkd/blob/master/package.json#L22

How are you compiling the example?

**Comment by nomad-software** [comment]
Closed due to lack of feedback.
