### ISSUE TITLE
start TK in D Programming !

### ISSUE THREAD

**Issue by Mennohexo** [nomad-software/tkd#45]
Hi there,
i am completely new in D Programming and only want to start the example code for TK that is described HERE on the homepage.
For this i have gitcloned the 3 packages tcltk  tkd  x11  in the folder  /usr/local/GIT/.
Then i run the command  dub   inside any single folder and build it.

When i want to run the example TK D script the following results are seen -

$ dmd -I/usr/local/GIT/ hw_graphical2.d
hw_graphical2.d(1): Error: module tkdapplication is in file 'tkd/tkdapplication.d' which cannot be read
import path[0] = /usr/local/GIT/
import path[1] = /usr/include/dmd/phobos
import path[2] = /usr/include/dmd/druntime/import
hans@mx1:~/Documents/D_lang
$ 

I have made something wrong with the configuration of the TKD module.
Need help here to start programming with D  and TK.

WBR
MHE

**Comment by nomad-software** [comment]
Hi,

Thanks for the question but this is a place to raise and discuss issues with the Tkd library itself. If you need help with the D programming language or how to build and use such libraries using Dub please ask here: http://forum.dlang.org/group/learn

Thank you.

**Comment by Mennohexo** [comment]
oh sorry. i will do that.

**Comment by nomad-software** [comment]
No worries. The guys are really helpful over at: http://forum.dlang.org/group/learn

**Comment by nomad-software** [comment]
You can also post on stackoverflow.com too, tagging your question with 'D'
