### ISSUE TITLE
Changing Widget Background Color

### ISSUE THREAD

**Issue by alexiusacademia** [nomad-software/tkd#47]
I was wondering if it is possible to change widget's background color like from Python's Tkinter:

```python
<widget>.configure(backgrounf="red")
```

Thanks

**Comment by nomad-software** [comment]
Not at the minute, I don't think but it would be easy to add.

**Comment by alexiusacademia** [comment]
Okay thank you very much. I will give it a try on my project and hope that it works for me.

**Comment by nomad-software** [comment]
This has been added by another contributor.

https://github.com/nomad-software/tkd/pull/51
