### ISSUE TITLE
How to install this in Windows ?

### ISSUE THREAD

**Issue by vinodvinu** [nomad-software/tkd#60]
How to install this in Windows ?

**Comment by nomad-software** [comment]
https://github.com/nomad-software/tkd#windows-1

**Comment by vinodvinu** [comment]
I did as you said in the read me file. This is my folder now looks like.
![Captured_000031](https://user-images.githubusercontent.com/8840907/81928135-7083ac80-9602-11ea-85ff-e4b7dbb03560.jpg)
And this is the compiler message
![Captured_000032](https://user-images.githubusercontent.com/8840907/81928323-b3458480-9602-11ea-8362-d7a65772c3e0.jpg)

**Comment by nomad-software** [comment]
That error message is because the DMD compiler cannot find the source files it needs. The `-I` switch needs the path to the appropriate source files. Using `rdmd` or [dub](https://dub.pm/getting_started) would probably be easier in this case.
