### ISSUE TITLE
Simple Q: is the final app using this lib completely native?

### ISSUE THREAD

**Issue by mw66** [nomad-software/tkd#66]
I am asking because I saw this in the doc:
```
project
├── app.exe
├── tcl86t.dll
├── tk86t.dll
└── library
    └── *.tcl files
```

I'm just wondering if the.tcl files needed at all?

is the final app using this lib completely native?

Thanks!

**Comment by nomad-software** [comment]
On Windows all those files are required.

**Comment by mw66** [comment]
Maybe I didn't make my question clear:

Can I completely get rid of those .tcl files, and do everything in D? and make the app.exe standalone.

I have tried the example.d, I think the answer is yes.

**Comment by nomad-software** [comment]
> Can I completely get rid of those .tcl files, and do everything in D?

No. On Windows all those files are required.
